-- BE-19 + PERF-22 + T-12 (the only 0001; generated by drizzle-kit, then ordered by hand).
-- Backfill NULLs before SET NOT NULL, convert the naive timestamps as UTC instants
-- (independent of the session TimeZone), mark every existing post as Turkish (T-12:
-- the live posts are TR) and keep lang mandatory for new rows (no default).
UPDATE "posts" SET "published" = false WHERE "published" IS NULL;--> statement-breakpoint
UPDATE "posts" SET "created_at" = now() WHERE "created_at" IS NULL;--> statement-breakpoint
UPDATE "posts" SET "updated_at" = "created_at" WHERE "updated_at" IS NULL;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "created_at" SET DATA TYPE timestamp with time zone USING "created_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "updated_at" SET DATA TYPE timestamp with time zone USING "updated_at" AT TIME ZONE 'UTC';--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "created_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "updated_at" SET DEFAULT now();--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "published" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "updated_at" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "posts" ADD COLUMN "published_at" timestamp with time zone;--> statement-breakpoint
UPDATE "posts" SET "published_at" = "created_at" WHERE "published" = true;--> statement-breakpoint
ALTER TABLE "posts" ADD COLUMN "lang" text DEFAULT 'tr' NOT NULL;--> statement-breakpoint
ALTER TABLE "posts" ALTER COLUMN "lang" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_lang_check" CHECK ("posts"."lang" in ('en', 'tr'));--> statement-breakpoint
ALTER TABLE "posts" ADD COLUMN "translation_key" text;--> statement-breakpoint
ALTER TABLE "posts" ADD CONSTRAINT "posts_translation_key_lang_unique" UNIQUE("translation_key","lang");--> statement-breakpoint
ALTER TABLE "posts" ADD COLUMN "seo_title" text;--> statement-breakpoint
CREATE INDEX "posts_lang_published_created_at_idx" ON "posts" USING btree ("lang","published","created_at" DESC NULLS FIRST);--> statement-breakpoint
CREATE INDEX "posts_published_created_at_idx" ON "posts" USING btree ("created_at" DESC NULLS FIRST) WHERE "posts"."published" = true;
