#!/usr/bin/env bun
/**
 * Builds the self-hosted font layer (PERF-08 / ANL-17):
 *
 *   public/fonts/v1/*.woff2   copied from @fontsource/{raleway,marcellus}
 *   public/fonts/v1/OFL.txt   licence + copyright of both families (SIL OFL 1.1)
 *   src/styles/fonts.css      @font-face rules, generated from faces.ts
 *
 *   bun scripts/fonts/sync-fonts.ts           # write
 *   bun scripts/fonts/sync-fonts.ts --check   # exit 1 when a file is out of date
 *
 * The folder is versioned (`v1`): /fonts/ is served `immutable` (W1), so a
 * changed font file goes into `v2/` and the CSS and preload links point there.
 */
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { format, resolveConfig } from "prettier";
import {
  FACES,
  FALLBACK_FACES,
  faceFile,
  faceUrl,
  type Face,
  type FallbackFace,
} from "./faces";

const ROOT = join(import.meta.dirname, "..", "..");
const FONTSOURCE = join(ROOT, "node_modules", "@fontsource");
export const FONT_DIR = join(ROOT, "public", "fonts", "v1");
export const CSS_FILE = join(ROOT, "src", "styles", "fonts.css");

function unicodeRange(face: Face): string {
  const json = JSON.parse(
    readFileSync(join(FONTSOURCE, face.pkg, "unicode.json"), "utf8"),
  ) as Record<string, string>;
  const range = json[face.subset];
  if (!range) {
    throw new Error(`no unicode-range for ${face.pkg} ${face.subset}`);
  }
  return range;
}

function pkgVersion(pkg: string): string {
  return JSON.parse(readFileSync(join(FONTSOURCE, pkg, "package.json"), "utf8"))
    .version as string;
}

function faceRule(face: Face): string {
  return `@font-face {
  font-family: "${face.family}";
  font-style: ${face.style};
  font-weight: ${face.weight};
  font-display: swap;
  src: url("${faceUrl(face)}") format("woff2");
  unicode-range: ${unicodeRange(face)};
}`;
}

function fallbackRule(f: FallbackFace): string {
  const src = f.local.map((n) => `local("${n}")`).join(", ");
  return `@font-face {
  font-family: "${f.name}";
  font-style: normal;
  font-weight: ${f.weight};
  src: ${src};
  size-adjust: ${f.sizeAdjust}%;
  ascent-override: ${f.ascent}%;
  descent-override: ${f.descent}%;
  line-gap-override: ${f.lineGap}%;
}`;
}

/** The text of src/styles/fonts.css. */
export async function renderFontsCss(): Promise<string> {
  const header = `/* GENERATED by scripts/fonts/sync-fonts.ts from scripts/fonts/faces.ts: do not
   edit by hand (\`bun scripts/fonts/sync-fonts.ts\`; tests/frontend/fonts checks it).
   Self-hosted Raleway ${pkgVersion("raleway")} and Marcellus ${pkgVersion("marcellus")} (SIL OFL 1.1, public/fonts/v1/OFL.txt).
   Each face is split into latin and latin-ext by unicode-range, so a page
   downloads only the files its text needs. The "* Fallback" faces are local
   system fonts scaled to the webfont's metrics, so the swap moves no text. */
`;
  const webfonts = (["Marcellus", "Raleway"] as const).map((family) =>
    FACES.filter((f) => f.family === family)
      .map(faceRule)
      .join("\n\n"),
  );
  const fallbacks = FALLBACK_FACES.map(fallbackRule).join("\n\n");
  const css = `${header}\n${webfonts.join("\n\n")}\n\n${fallbacks}\n`;
  // The repo runs prettier --check; format here so a regenerate never drifts.
  const options = (await resolveConfig(CSS_FILE)) ?? {};
  return format(css, { ...options, parser: "css" });
}

const OFL_HEAD = `Copyright (c) 2012 by Brian J. Bonislawsky DBA Astigmatic (AOETI)
(astigma@astigmatic.com), with Reserved Font Name "Marcellus"

Copyright 2010 The Raleway Project Authors (impallari@gmail.com), with
Reserved Font Name "Raleway".

This Font Software is licensed under the SIL Open Font License, Version 1.1.
This license is copied below, and is also available with a FAQ at:
https://openfontlicense.org
`;

/** The licence text both @fontsource packages ship (the same for the two). */
export function renderOfl(): string {
  const licence = readFileSync(
    join(FONTSOURCE, "marcellus", "LICENSE"),
    "utf8",
  );
  const marker = "-----------------------------------------------------------";
  const at = licence.indexOf(marker);
  if (at < 0) throw new Error("OFL marker not found in @fontsource licence");
  return `${OFL_HEAD}\n\n${licence.slice(at).trimEnd()}\n`;
}

function differs(path: string, content: Buffer): boolean {
  return !existsSync(path) || Buffer.compare(readFileSync(path), content) !== 0;
}

/** Writes (or, with `check`, only verifies) every generated file; returns the out-of-date paths. */
export async function sync(check: boolean): Promise<string[]> {
  const stale: string[] = [];
  if (!check) mkdirSync(FONT_DIR, { recursive: true });
  for (const face of FACES) {
    const from = join(FONTSOURCE, face.pkg, "files", faceFile(face));
    const to = join(FONT_DIR, faceFile(face));
    if (!existsSync(from)) throw new Error(`missing ${from}`);
    if (differs(to, readFileSync(from))) {
      stale.push(to);
      if (!check) copyFileSync(from, to);
    }
  }
  const texts: [string, string][] = [
    [join(FONT_DIR, "OFL.txt"), renderOfl()],
    [CSS_FILE, await renderFontsCss()],
  ];
  for (const [path, text] of texts) {
    if (differs(path, Buffer.from(text))) {
      stale.push(path);
      if (!check) writeFileSync(path, text);
    }
  }
  return stale;
}

// Run as a script only (vitest imports renderFontsCss/sync without running it).
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const check = process.argv.includes("--check");
  const stale = await sync(check);
  if (check) {
    for (const path of stale) console.error(`out of date: ${path}`);
    process.exit(stale.length ? 1 : 0);
  }
  console.log(
    stale.length
      ? `fonts synced (${stale.length} files)`
      : "fonts already up to date",
  );
}
