// The home hero photo (PERF-02, FE-18, SEO-26, DSG-29): one set of files
// for every plan, generated by scripts/images/build-responsive.ts (preset
// "hero") into public/img/hero/ and served from /img/ with a one-year
// immutable cache (W1, T-11).
//
// The file names carry no hash, so `version` is the content version: a new
// photo or crop must be written as v2 (and the preset bumped with it),
// never over v1, or browsers and the CDN keep the old bytes for a year.
//
// This module is the single source for the names, the widths and the
// `sizes` value: the <picture> in ./index.jsx and the generator both read
// it, so a width cannot exist in the markup without a file behind it.
export const HERO_IMAGE = Object.freeze({
  dir: "/img/hero",
  name: "cengizhan-kose",
  version: "v1",
  // 768w on purpose (PERF-02 step 4): a 412px phone at DPR 1.75 needs
  // ~721px, and without it the browser would pick 1000w.
  widths: Object.freeze([640, 768, 1000, 1284]),
  // Intrinsic size of the largest file; the width/height attributes give
  // the browser the aspect ratio before any byte arrives (DSG-29, no CLS).
  width: 1284,
  height: 1654,
  // Plain <img src> for browsers without srcset support.
  fallbackWidth: 768,
  // The photo is the full column below 992px (Bootstrap lg) and half the
  // viewport from there on (./home.module.css). object-fit: cover crops the
  // height, so the width decides: every common desktop column (50vw x
  // 100vh) and the mobile 4:5 box are wider than the 1284:1654 photo.
  sizes: "(max-width: 991.98px) 100vw, 50vw",
});

/** Site path of one variant, e.g. /img/hero/cengizhan-kose-v1-768.avif. */
export function heroSrc(width, ext) {
  const { dir, name, version } = HERO_IMAGE;
  return `${dir}/${name}-${version}-${width}.${ext}`;
}

/** srcset value for one format: every width, ascending, with its w descriptor. */
export function heroSrcSet(ext) {
  return HERO_IMAGE.widths.map((w) => `${heroSrc(w, ext)} ${w}w`).join(", ");
}
