// Site-wide identity constants (T-03). Pure ESM with no React and no browser
// globals: the Bun server (head injection, sitemap) and the Vite client import
// the same file. Per-page metadata lives in src/seo/pages.js; nothing else in
// src/ defines these values.

// K-03: www is the canonical host. No trailing slash.
export const SITE_URL = "https://www.cengizhankose.com";

// T-07: the name is always spelled "Köse" (never in capitals).
export const SITE_NAME = "Cengizhan Köse";

// T-12: EN is the default locale (no path prefix, x-default); TR lives under /tr.
export const LOCALES = Object.freeze(["en", "tr"]);
export const DEFAULT_LOCALE = "en";

// Role from 00-icerik-girdileri.md §2.1/§2.4 (recommended default). The TR
// pages keep the English role as well.
export const AUTHOR = Object.freeze({
  name: SITE_NAME,
  jobTitle: "Senior Fullstack Engineer",
  url: SITE_URL,
});

// K-11: the six active channels, in this order. `id` values are the analytics
// NETWORKS enum (ANL-19) without "other". URLs: 00-icerik-girdileri.md §8.
// Facebook is gone (K-11).
export const SOCIAL_PROFILES = Object.freeze(
  [
    {
      id: "linkedin",
      label: "LinkedIn",
      url: "https://www.linkedin.com/in/cengizhankose",
    },
    { id: "github", label: "GitHub", url: "https://github.com/cengizhankose" },
    { id: "x", label: "X", url: "https://x.com/cengzhnkse" },
    {
      id: "youtube",
      label: "YouTube",
      url: "https://www.youtube.com/@cengizhankse",
    },
    {
      id: "twitch",
      label: "Twitch",
      url: "https://www.twitch.tv/cengizhankose",
    },
    {
      id: "instagram",
      label: "Instagram",
      url: "https://www.instagram.com/cengizhankse/",
    },
  ].map((profile) => Object.freeze(profile)),
);

// Default share image generated by W1-DSG-brand-assets (public/og/default.jpg).
// Site-relative; the og:image renderer (SEO-06) prefixes SITE_URL.
export const DEFAULT_OG_IMAGE = "/og/default.jpg";
export const DEFAULT_OG_IMAGE_SIZE = Object.freeze({
  width: 1200,
  height: 630,
  type: "image/jpeg",
});

// T-07 title pattern: "<Topic> | Cengizhan Köse". Without a topic the bare
// site name is returned. Surrounding whitespace never reaches the title.
export function buildTitle(topic) {
  const text = typeof topic === "string" ? topic.trim() : "";
  return text ? `${text} | ${SITE_NAME}` : SITE_NAME;
}

// T-07 home-page pattern: "Cengizhan Köse | <role>".
export function buildHomeTitle(role = AUTHOR.jobTitle) {
  const text = typeof role === "string" ? role.trim() : "";
  return text ? `${SITE_NAME} | ${text}` : SITE_NAME;
}
