// Site-wide identity constants (T-03). Pure ESM with no React and no browser
// globals: the Bun server (head injection, sitemap) and the Vite client import
// the same file. Per-page metadata lives in src/seo/pages.js; nothing else in
// src/ defines these values.

// K-03: www is the canonical host. No trailing slash.
export const SITE_URL = "https://www.cengizhankose.com";

// T-07: the name is always spelled "Köse" (never in capitals).
export const SITE_NAME = "Cengizhan Köse";

// T-12: EN is the default locale (no path prefix, x-default); TR lives under /tr.
export const LOCALES = Object.freeze(["en", "tr"]);
export const DEFAULT_LOCALE = "en";

// Role from 00-icerik-girdileri.md §2.1/§2.4 (recommended default). The TR
// pages keep the English role as well; jobTitles is the one place to change
// that per language.
const ROLE = "Senior Fullstack Engineer";

// Person facts printed by the JSON-LD (SEO-07) and shared with the About page.
// Every value comes from 00-icerik-girdileri.md and must also be visible on
// /about (SEO-07 criterion 2). A property without a source value is left out,
// never guessed (no Drivee URL in the content inputs, so worksFor has no url).
//   worksFor: employers with no end date in §3.1 (Drivee Teknoloji, since
//             2026-01; the role before it was also at Drivee).
//   awards:   the first places of §5, newest first, written "<event> (<year>)".
//             The event names are proper nouns and stay the same in both
//             languages. W6-MKT-about-positioning renders the same strings.
export const AUTHOR = Object.freeze({
  name: SITE_NAME,
  jobTitle: ROLE,
  jobTitles: Object.freeze({ en: ROLE, tr: ROLE }),
  url: SITE_URL,
  worksFor: Object.freeze([Object.freeze({ name: "Drivee Teknoloji" })]),
  awards: Object.freeze([
    "ConvoAI World Istanbul (2026)",
    "AlgoHack Istanbul (2025)",
    "Teknasyon Yüzük Kardeşliği Hackathon (2022)",
    "Sosyal Uyum için İnovatif Çözümler Hackathonu (2021)",
  ]),
});

// K-11: the six active channels, in this order, and nothing else. `id` values
// are the analytics NETWORKS enum (ANL-19) without "other". URLs:
// 00-icerik-girdileri.md §8. The one social list of the site: the side rail
// and the menu footer (SocialLinks), and the JSON-LD sameAs (SEO-07).
export const SOCIAL_PROFILES = Object.freeze(
  [
    {
      id: "linkedin",
      label: "LinkedIn",
      url: "https://www.linkedin.com/in/cengizhankose",
    },
    { id: "github", label: "GitHub", url: "https://github.com/cengizhankose" },
    { id: "x", label: "X", url: "https://x.com/cengzhnkse" },
    {
      id: "youtube",
      label: "YouTube",
      url: "https://www.youtube.com/@cengizhankse",
    },
    {
      id: "twitch",
      label: "Twitch",
      url: "https://www.twitch.tv/cengizhankose",
    },
    {
      id: "instagram",
      label: "Instagram",
      url: "https://www.instagram.com/cengizhankse/",
    },
  ].map((profile) => Object.freeze(profile)),
);

// Default share image generated by W1-DSG-brand-assets (public/og/default.jpg).
// Site-relative; absoluteUrl() prefixes SITE_URL for og:image (SEO-06).
export const DEFAULT_OG_IMAGE = "/og/default.jpg";
export const DEFAULT_OG_IMAGE_SIZE = Object.freeze({
  width: 1200,
  height: 630,
  type: "image/jpeg",
});

// Portrait printed as Person.image (SEO-07, SEO-26). One fixed hero path
// generated by W6-DSG-hero-image-lcp (public/img/hero/, 1284 px wide JPEG).
export const HERO_IMAGE = "/img/hero/cengizhan-kose-v1-1284.jpg";

// SEO-06 step 2: og:locale values of the site's languages (T-12).
export const OG_LOCALE = Object.freeze({ en: "en_US", tr: "tr_TR" });

// SEO-06 step 3: twitter:site and twitter:creator. X is an active channel
// (K-11); the handle is the one in the X entry of SOCIAL_PROFILES.
export const TWITTER_HANDLE = "@cengzhnkse";

// Absolute URL for a site-relative path ("/og/default.jpg"). Absolute http(s)
// URLs are returned as they are, so a post's coverImage can be either.
export function absoluteUrl(value) {
  const text = typeof value === "string" ? value.trim() : "";
  if (!text) return "";
  if (/^https?:\/\//i.test(text)) return text;
  if (text.startsWith("//")) return `https:${text}`;
  return `${SITE_URL}${text.startsWith("/") ? "" : "/"}${text}`;
}

// T-07 title pattern: "<Topic> | Cengizhan Köse". Without a topic the bare
// site name is returned. Surrounding whitespace never reaches the title.
export function buildTitle(topic) {
  const text = typeof topic === "string" ? topic.trim() : "";
  return text ? `${text} | ${SITE_NAME}` : SITE_NAME;
}

// T-07 home-page pattern: "Cengizhan Köse | <role>".
export function buildHomeTitle(role = AUTHOR.jobTitle) {
  const text = typeof role === "string" ? role.trim() : "";
  return text ? `${SITE_NAME} | ${text}` : SITE_NAME;
}
