// Podium photos of the portfolio's hackathon section (W13): one square set
// per award, generated by scripts/images/build-responsive.ts (presets
// "award-<name>") into public/img/awards/ and served from /img/ with the
// one-year immutable cache. Same rules as projectImage.js: no hash in the
// names, so `version` is the content version (a new crop is v2, never over
// v1), and this module is the single source of names, widths and `sizes` for
// both the <picture> and the generator.
//
// The tile is a 6.5rem thumbnail beside the text below 768px and a third of
// the row from there on (portfolio.module.css). A record whose source photo
// is smaller than the largest width lists its own `widths`
// (src/content/awards.js), so nothing is ever upscaled.
export const AWARD_IMAGE = Object.freeze({
  dir: "/img/awards",
  version: "v1",
  widths: Object.freeze([320, 640]),
  sizes: "(min-width: 768px) 30vw, 6.5rem",
  // Photos, square: each file at most 80 KB.
  maxBytes: 80 * 1024,
});

/** The widths of one award image (its own list, else the default). */
export const awardWidths = (image) => image.widths ?? AWARD_IMAGE.widths;

/** Site path of one variant, e.g. /img/awards/teknasyon-2022-v1-320.webp. */
export function awardSrc(name, width, ext) {
  const { dir, version } = AWARD_IMAGE;
  return `${dir}/${name}-${version}-${width}.${ext}`;
}

/** srcset value for one format: every width, ascending, with its w descriptor. */
export function awardSrcSet(image, ext) {
  return awardWidths(image)
    .map((width) => `${awardSrc(image.name, width, ext)} ${width}w`)
    .join(", ");
}
