// Card images of the portfolio (FE-04, DSG-08, DSG-29): one set of files per
// case, generated by scripts/images/build-responsive.ts (presets
// "portfolio-<name>") into public/img/projects/ and served from /img/ with
// the one-year immutable cache (W1, T-11).
//
// Same rules as the hero photo (src/pages/home/heroImage.js): the names carry
// no hash, so `version` is the content version. A new crop is written as v2
// and the preset bumped with it, never over v1.
//
// Single source for names, widths and `sizes`: the card's <picture> and the
// generator both read it, so a width cannot be in the markup without a file
// behind it. Images are 16:10 (DSG-08), each file at most `maxBytes`.
export const PROJECT_IMAGE = Object.freeze({
  dir: "/img/projects",
  version: "v1",
  widths: Object.freeze([480, 800, 1280]),
  // Intrinsic size of the largest file (width/height attributes: no CLS).
  width: 1280,
  height: 800,
  // Plain <img src> for browsers without srcset support.
  fallbackWidth: 800,
  // The grid is three columns from 992px (Bootstrap lg), one below.
  sizes: "(min-width: 992px) 33vw, 100vw",
  // DSG-08 / FE-04: no card image is larger than 150 KB.
  maxBytes: 150 * 1024,
});

/** File name slug of a project id: effort_lab -> effort-lab (SEO-26: hyphens). */
export const projectImageName = (id) => String(id).replaceAll("_", "-");

/** Site path of one variant, e.g. /img/projects/salesgym-v1-800.webp. */
export function projectSrc(name, width, ext) {
  const { dir, version } = PROJECT_IMAGE;
  return `${dir}/${name}-${version}-${width}.${ext}`;
}

/** srcset value for one format: every width, ascending, with its w descriptor. */
export function projectSrcSet(name, ext) {
  return PROJECT_IMAGE.widths
    .map((width) => `${projectSrc(name, width, ext)} ${width}w`)
    .join(", ");
}
